name: Build 11ty & Deploy with ssh+rsync

env:
  TZ: 'Asia/Tokyo'

on:
  push:
    branches: master
  repository_dispatch:
    types: [cms_update]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.0'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_URL: ${{ secrets.API_URL }}
    - name: Deploy to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete --bwlimit=3096"
          FOLDER: "./_build/"
          SERVER_IP: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          SERVER_PORT: ${{ secrets.REMOTE_PORT }}
          SERVER_DESTINATION: ${{ secrets.REMOTE_TARGET }}
